name: Java OOP Check

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Compile Java projects
      run: |
        for dir in projects/*; do
          if [ -d "$dir" ]; then
            echo "Compiling project: $dir"

            mkdir -p "$dir/classes"

            find "$dir" -name "*.java" > sources.txt

            if [ -s sources.txt ]; then
              javac -d "$dir/classes" @sources.txt
            fi
          fi
        done