name: Java OOP Check

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Compile Java projects
      run: |
        find . -name "*.java" | awk -F/ '{print $2}' | sort -u | while read dir; do
          echo "Compiling project: $dir"

          files=$(find "$dir" -name "*.java")

          if [ -n "$files" ]; then
            mkdir -p "$dir/classes"
            javac -d "$dir/classes" $files
          fi
        done